### ISSUE TITLE
ASM: 'network application-gateway http-listener add' not working properly

### ISSUE THREAD

**Issue by HimanshuBri** [MSOpenTech/azure-xplat-cli#328]
Taking Http as Https
Please see code snippet below.
<code><pre>E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network>node bin/azure network application-gateway http-listener add --gateway-name Testappgate7 --name Testhttplist1 --frontend-ip-name fip1 --protocol http --frontend-port-name Testfrontport1
info:    Executing command network application-gateway http-listener add
+ Getting configuration for an application gateway "Testappgate7"
error:   --ssl-cert parameter is required when "--protocol Https" parameter is specified
info:    Error information has been recorded to C:\Users\himanshu.agarwal\.azure\azure.err
error:   network application-gateway http-listener add command failed
</pre></code>

**Comment by HimanshuBri** [comment]
Please check below code snippet as well. <code><pre>E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network>node bin/azure network application-gateway http-listener add --gateway-name Testappgate7 --name Testhttplist1 --frontend-ip-name fip1 --protocol https --frontend-port-name Testfrontport1 -c E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\test\myCert.pem -v
info:    Executing command network application-gateway http-listener add
verbose: Getting configuration for an application gateway "Testappgate7"
verbose: Setting configuration for an application gateway "Testappgate7"
error:   The specified request content was not valid and could not be deserialized.
info:    Error information has been recorded to C:\Users\himanshu.agarwal\.azure\azure.err
verbose: Error: The specified request content was not valid and could not be deserialized.
    at Function.ServiceClient._normalizeError (E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\serviceclient.js:815:23)
    at E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\services\filters\errorhandlingfilter.js:44:29
    at Request._callback (E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\lib\http\request-pipeline.js:109:14)
    at Request.self.callback (E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\request.js:199:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\request.js:1160:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (E:\4486\15-June-2015\azure-xplat-cli-dev-asm-network\node_modules\azure-mgmt-vnet\node_modules\azure-common\node_modules\request\request.js:1111:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16

error:   network application-gateway http-listener add command failed
</pre></code>

**Comment by MikhailTryakhov** [comment]
@HimanshuBri thank you! Currently, it should be fixed.

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Thanks. Working fine for Http. Giving error for Https. Please check the code snippet.<code><pre>E:\4486\16-June-2015\azure-xplat-cli-dev-asm-network>node bin/azure network application-gateway http-listener add --gateway-name Testappgate --name Testhttplist2 --frontend-ip-name fip1 --protocol https --frontend-port-name fep1 -c E:\4486\16-June-2015\azure-xplat-cli-dev-asm-network\test\myCert.pem
info:    Executing command network application-gateway http-listener add
+ Getting configuration for an application gateway "Testappgate"
+ Setting configuration for an application gateway "Testappgate"
error:   InternalError : Certificate E:\4486\16-June-2015\azure-xplat-cli-dev-asm-network\test\myCert.pem referenced in config is not found.
info:    Error information has been recorded to C:\Users\himanshu.agarwal\.azure\azure.err
error:   network application-gateway http-listener add command failed</pre></code>

**Comment by MikhailTryakhov** [comment]
thanks @HimanshuBri  I'm working on it

**Comment by MikhailTryakhov** [comment]
Hi @HimanshuBri,
this error shows that the specified certificate was not found. Please check was the address correct

**Comment by HimanshuBri** [comment]
@MikhailTryakhov. Verified once again path is correct but still getting the same error.
